muscles = [
    "",
    "   - = мышцы верхней конечности = -",
    "m.abductor pollicis (мышца, отводящая большой палец)",
    "m.adductor pollicis (мышца, приводящая большой палец)",
    "m.biceps brachii (двуглавая мышца)",
    "m.brachialis (плечевая мышца)",
    "m.brachioradialis (плечелучевая мышца)",
    "m.deltoideus (дельтовидная мышца)",
    "m.flexor carpi radialis (лучевой сгибатель запястья)",
    "m.flexor carpi ulnaris (локтевой сгибатель запястья)",
    "m.flexor digitorum profundus (глубокий сгибатель пальцев)",
    "m.flexor digitorum superficialis (поверхностный сгибатель пальцев)",
    "m.flexor pollicis brevis (короткий сгибатель большого пальца)",
    "m.flexor pollicis longus (длинный сгибатель большого пальца)",
    "m.interossei dorsales (тыльные межкостные мышцы)",
    "m.interossei palmares (ладонные межкостные мышцы)",
    "m.latissimus dorsi (широчайшая мышца спины)",
    "m.lumbricalis (червеобразная мышца)",
    "m.opponens pollicis (мышца, противопоставляющая большой палец)",
    "m.pectoralis major (большая грудная мышца)",
    "m.pronator teres (круглый пронатор)",
    "m.supinator (мышца-супинатор)",
    "m.teres major (большая круглая мышца)",
    "m.triceps brachii (трехглавая мышца плеча)",
    "   - = мышцы нижней конечности = -",
    "m.adductor brevis (короткая приводящая мышца)",
    "m.adductor longus (длинная приводящая мышца)",
    "m.adductor magnus (большая приводящая мышца)",
    "m.biceps femoris (двуглавая мышца бедра)",
    "m.extensor digitorum longus (длинный разгибатель пальцев)",
    "m.extensor hallucis longus (длинный разгибатель большого пальца стопы)",
    "m.flexor digitorum brevis (короткий сгибатель пальцев)",
    "m.flexor digitorum longus (длинный сгибатель пальцев)",
    "m.flexor hallucis brevis (короткий сгибатель большого пальца стопы)",
    "m.flexor hallucis longus (длинный сгибатель большого пальца стопы)",
    "m.gastrocnemius (икроножная мышца)",
    "m.gracilis (тонкая мышца)",
    "m.iliacus (подвздошная мышца)",
    "m.iliopsoas (подвздошно-поясничная мышца)",
    "m.peroneus longus (длинная малоберцовая мышца)",
    "m.psoas major (большая поясничная мышца)",
    "m.rectus femoris (прямая мышца бедра)",
    "m.sartorius (портняжная мышца)",
    "m.semitendinosus (полусухожильная мышца)",
    "m.semimembranosus (полуперепончатая мышца)",
    "m.soleus (камбаловидная мышца)",
    "m.tibialis anterior (передняя большеберцовая мышца)",
    "m.tibialis posterior (задняя большеберцовая мышца)",
    "m.vastus intermedius (промежуточная широкая мышца бедра)",
    "m.vastus lateralis (латеральная широкая мышца бедра)",
    "m.vastus medialis (медиальная широкая мышца бедра)",
]
